# Generated by Django 3.2 on 2022-05-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_ratingreview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
